name: fe-pos-quickshop

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.0
      
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web
      
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_PAGE_TOKEN }}
          command: |
            pages deploy ./build/web --project-name=cf-deploy-test
  
  notification:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project has been deployed.'