name: fe-pos-quickshop

on:
  push:
    branches:
      - main
  pull_request: ~

env:
  GLOBAL_DISCORD_EMBEDS: |
    {
      "author": {
        "name": "${{ github.actor }}",
        "url": "${{ github.server_url }}/${{ github.actor }}",
        "icon_url": "${{ github.server_url }}/${{ github.actor }}.png?size=32"
      },
      "title": "${{ github.workflow }}",
      "description": "${{ github.ref }}",
      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web
      
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_PAGE_TOKEN }}
          command: |
            pages deploy ./build/web --project-name=${{ secrets.CF_PROJECT_NAME }}
  
  notification:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Send successful notification to discord
        if: ${{ needs.deploy.result == 'success' }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": ":rocket: Build successfully",
                "color": "1127128"
              },
              ${{ env.GLOBAL_DISCORD_EMBEDS }}
            ]
            
      - name: Send failure notification to discord
        if: ${{ needs.deploy.result == 'failure' }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": ":broken_heart: Build failure please check.",
                "color": "14177041"
              },
              ${{ env.GLOBAL_DISCORD_EMBEDS }}
            ]
      